services:
  - type: web
    name: restaurante-patagonia
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python init_db.py
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: SECRET_KEY
        generateValue: true
      - key: BASE_URL
        value: https://restaurante-patagonia.onrender.com 